### PR TITLE
fix: syscoin should not be litecoin in chinese

### PR DESCRIPTION
**Pull request by laishulu**

### CODE REVIEW

**Comment by laishulu** [comment]
Is PR not welcome in this project?

I have not see any reponse to it from both github and BCT.

**Comment by Snipsnoop** [comment]
Hi chenhouwu

Oh we do welcome PR.. And thank you for your effort, this will be merged when we do the next release

**Comment by dwasyluk** [comment]
After review this only impacts translation files and can be merged directly to master. Thanks for the fix!

**Comment by laishulu** [comment]
sigh.....
In the 0.1.5 RC1, the patch is not applied yet.

**Comment by dwasyluk** [comment]
This will be merged into devstaging-0.1.5 - https://github.com/syscoin/syscoin/issues/25

**Pull request merged**
